services:
    app:
        build:
            context: .
        container_name: laravel_api
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
            - ./bootstrap/cache:/var/www/bootstrap/cache
            - ./.env:/var/www/.env
        ports:
            - "8000:8000"
        depends_on:
            - db


    db:
        image: mysql:8.0.32
        container_name: laravel_db
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=task_manager
            - MYSQL_USER=laravel_user
            - MYSQL_PASSWORD=root
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
